### ISSUE TITLE
Crash in tls_configure_ssl_verify

### ISSUE THREAD

**Issue by graywolf** [libressl-portable/portable#682]
Hello,

I'm trying to use libressl to connect to https server, part of my code looks
like:

```
446 #if WITH_LIBTLS
  1         if ((http->ctx = tls_client()) == NULL) {
  2                 warn("tls_client");
  3                 goto err;
  4         } else if (tls_configure(http->ctx, tlscfg) == -1) {
  5                 warnx("%s: tls_configure: %s",
  6                         http->src.ip, tls_error(http->ctx));
  7                 goto err;
  8         }
  9
 10         if (tls_connect_socket(http->ctx, http->fd, http->host) != 0) {
 11                 warnx("%s: tls_connect_socket: %s, %s", http->src.ip,
 12                     http->host, tls_error(http->ctx));
 13                 goto err;
 14         }
```

However, when I try to run it I'm welcomed with SIGSEGV and the backtrace looks
like this:

```
Thread 2.1 "acme-client" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff794c1c0 (LWP 81026)]
0x00007ffff7c5e2a3 in by_mem_ctrl (lu=0x5555555859e0, cmd=<optimized out>,
    buf=<optimized out>, type=<optimized out>, ret=<optimized out>) at x509/by_mem.c:115
115     x509/by_mem.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7c5e2a3 in by_mem_ctrl (lu=0x5555555859e0, cmd=<optimized out>,
    buf=<optimized out>, type=<optimized out>, ret=<optimized out>) at x509/by_mem.c:115
#1  0x00007ffff7c67890 in X509_STORE_load_mem (ctx=0x555555586fb0, buf=0x7ffff78f9010,
    len=335615) at x509/x509_d2.c:124
#2  0x00007ffff7b754a0 in tls_configure_ssl_verify (ctx=ctx@entry=0x555555587b90,
    ssl_ctx=0x555555587c40, verify=verify@entry=1) at tls.c:599
#3  0x00007ffff7b75edd in tls_connect_common (ctx=ctx@entry=0x555555587b90,
    servername=0x555555587190 "localhost") at tls_client.c:315
#4  0x00007ffff7b76396 in tls_connect_fds (ctx=0x555555587b90, fd_read=3, fd_write=3,
    servername=<optimized out>) at tls_client.c:389
#5  0x000055555555d554 in http_alloc (addrs=0x7fffffffe860, addrsz=1,
    host=0x555555586480 "localhost", port=443, path=0x555555587b30 "/dir")
    at /x/usr.sbin/acme-client/http.c:456
#6  0x000055555555e25d in http_get (addrs=0x7fffffffe860, addrsz=1,
    domain=0x555555586480 "localhost", port=443, path=0x555555587b30 "/dir", headreq=0,
    post=0x0, postsz=0) at /x/usr.sbin/acme-client/http.c:850
#7  0x00005555555629e8 in nreq (c=0x7fffffffe9e0, addr=0x555555571620 "https://localhost/dir")
    at /x/usr.sbin/acme-client/netproc.c:206
#8  0x0000555555564000 in dodirs (c=0x7fffffffe9e0,
    addr=0x555555571620 "https://localhost/dir", paths=0x7fffffffe9c0)
    at /x/usr.sbin/acme-client/netproc.c:655
#9  0x0000555555564349 in netproc (kfd=4, afd=6, Cfd=8, cfd=10, dfd=14, rfd=16, revocate=0,
    authority=0x5555555715c0, alts=0x5555555705a0, altsz=2)
    at /x/usr.sbin/acme-client/netproc.c:757
#10 0x0000555555561dd7 in main (argc=0, argv=0x7fffffffeca8)
    at /x/usr.sbin/acme-client/main.c:217
```

Would anyone have any tips on what I might be doing wrong? Whole source code in
case it is needed can be found at [0].

0: https://git.sr.ht/~graywolf/acme-client-portable/tree/master/item/usr.sbin/acme-client/http.c#L446

**Comment by graywolf** [comment]
This was my fuck up, sorry for the spam.
