### ISSUE TITLE
Memory leak bugs

### ISSUE THREAD

**Issue by GoldBinocle** [libressl-portable/portable#687]
Hi, here are some memory leak bugs.

```
=================================================================
==2095819==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4d4862 in calloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5236d8 in CBB_init /root/projects/portable/ssl/bs_cbb.c:54:13
    #2 0x517776 in test_tlsext_sessionticket_server /root/projects/portable/tests/tlsexttest.c:2236:2
    #3 0x505845 in main /root/projects/portable/tests/tlsexttest.c:3630:12
    #4 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4d4862 in calloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5236d8 in CBB_init /root/projects/portable/ssl/bs_cbb.c:54:13
    #2 0x520ab3 in test_tlsext_clienthello_build /root/projects/portable/tests/tlsexttest.c:2745:7
    #3 0x5058a8 in main /root/projects/portable/tests/tlsexttest.c:3648:12
    #4 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4d4862 in calloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5236d8 in CBB_init /root/projects/portable/ssl/bs_cbb.c:54:13
    #2 0x521993 in test_tlsext_serverhello_build /root/projects/portable/tests/tlsexttest.c:2847:7
    #3 0x5058b3 in main /root/projects/portable/tests/tlsexttest.c:3649:12
    #4 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x4d4862 in calloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5a8fa6 in tls13_key_share_new /root/projects/portable/ssl/tls13_key_share.c:47:12
    #2 0x5a90cf in tls13_key_share_new_nid /root/projects/portable/ssl/tls13_key_share.c:64:9
    #3 0x51ae1f in test_tlsext_keyshare_server /root/projects/portable/tests/tlsexttest.c:3260:6
    #4 0x505871 in main /root/projects/portable/tests/tlsexttest.c:3636:12
    #5 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Direct leak of 17 byte(s) in 1 object(s) allocated from:
    #0 0x4d46ed in malloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x46b972 in strndup /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:397:3
    #2 0x526960 in CBS_strdup /root/projects/portable/ssl/bs_cbs.c:98:13
    #3 0x583c3f in tlsext_sni_server_parse /root/projects/portable/ssl/ssl_tlsext.c:774:8
    #4 0x513195 in test_tlsext_sni_client /root/projects/portable/tests/tlsexttest.c:1730:7
    #5 0x50580e in main /root/projects/portable/tests/tlsexttest.c:3623:12
    #6 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x4d4862 in calloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5a9540 in tls13_key_share_generate_x25519 /root/projects/portable/ssl/tls13_key_share.c:141:17
    #2 0x5a9461 in tls13_key_share_generate /root/projects/portable/ssl/tls13_key_share.c:164:10
    #3 0x51af9d in test_tlsext_keyshare_server /root/projects/portable/tests/tlsexttest.c:3262:7
    #4 0x505871 in main /root/projects/portable/tests/tlsexttest.c:3636:12
    #5 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x4d46ed in malloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x526750 in CBS_stow /root/projects/portable/ssl/bs_cbs.c:85:18
    #2 0x5a9d96 in tls13_key_share_peer_public_x25519 /root/projects/portable/ssl/tls13_key_share.c:250:9
    #3 0x5a9bf0 in tls13_key_share_peer_public /root/projects/portable/ssl/tls13_key_share.c:261:8
    #4 0x51b075 in test_tlsext_keyshare_server /root/projects/portable/tests/tlsexttest.c:3266:7
    #5 0x505871 in main /root/projects/portable/tests/tlsexttest.c:3636:12
    #6 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x4d4862 in calloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5a951e in tls13_key_share_generate_x25519 /root/projects/portable/ssl/tls13_key_share.c:139:16
    #2 0x5a9461 in tls13_key_share_generate /root/projects/portable/ssl/tls13_key_share.c:164:10
    #3 0x51af9d in test_tlsext_keyshare_server /root/projects/portable/tests/tlsexttest.c:3262:7
    #4 0x505871 in main /root/projects/portable/tests/tlsexttest.c:3636:12
    #5 0x7fa6ac2650b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 353 byte(s) leaked in 8 allocation(s).
```

**Comment by 4a6f656c** [comment]
These have likely been resolved and asan is now run via CI - please let us know if this is not the case.
