### ISSUE TITLE
regression caught by ruby-openssl test suite

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#795]
test run: https://github.com/chipitsine/ruby-openssl/actions/runs/3304324758/jobs/5453527017

```
12) Error: test_generalizedtime(OpenSSL::TestASN1): OpenSSL::ASN1::ASN1Error: invalid time format
/home/runner/work/ruby-openssl/ruby-openssl/test/openssl/test_asn1.rb:700:in `decode'
/home/runner/work/ruby-openssl/ruby-openssl/test/openssl/test_asn1.rb:700:in `decode_test'
/home/runner/work/ruby-openssl/ruby-openssl/test/openssl/test_asn1.rb:435:in `test_generalizedtime'
     432:       OpenSSL::ASN1::GeneralizedTime.new(Time.utc(2016, 12, 8, 19, 34, 29))
     433:     encode_decode_test B(%w{ 18 0F }) + "99990908234339Z".b,
     434:       OpenSSL::ASN1::GeneralizedTime.new(Time.utc(9999, 9, 8, 23, 43, 39))
  => 435:     decode_test B(%w{ 18 0D }) + "201612081934Z".b,
     436:       OpenSSL::ASN1::GeneralizedTime.new(Time.utc(2016, 12, 8, 19, 34, 0))
     437:     # not implemented
     438:     # decode_test B(%w{ 18 13 }) + "20161208193439+0930".b,

13) Error: test_utctime(OpenSSL::TestASN1): OpenSSL::ASN1::ASN1Error: invalid time format
/home/runner/work/ruby-openssl/ruby-openssl/test/openssl/test_asn1.rb:700:in `decode'
/home/runner/work/ruby-openssl/ruby-openssl/test/openssl/test_asn1.rb:700:in `decode_test'
/home/runner/work/ruby-openssl/ruby-openssl/test/openssl/test_asn1.rb:408:in `test_utctime'
     405:     encode_decode_test B(%w{ 17 0D }) + "160908234339Z".b,
     406:       OpenSSL::ASN1::UTCTime.new(Time.utc(2016, 9, 8, 23, 43, 39))
     407:     # Seconds is omitted
  => 408:     decode_test B(%w{ 17 0B }) + "1609082343Z".b,
     409:       OpenSSL::ASN1::UTCTime.new(Time.utc(2016, 9, 8, 23, 43, 0))
     410:     begin
     411:       # possible range of UTCTime is 1969-2068 currently

```

**Comment by botovq** [comment]
This is expected and known. It is a consequence of a deliberate change to make the ASN.1 time parser RFC 5280 compliant https://github.com/libressl-portable/openbsd/commit/eb5d07357320dedccf7ba866d9acfec88d7d1e34. This has stricter requirements than the ASN.1 standard. In particular, the parser no longer accepts times without seconds.

The way these tests are written, openssl-ruby checks for general ASN.1 compliance. In OpenBSD's regress framework, we patch ruby-openssl to provide seconds: https://github.com/openbsd/ports/blob/master/security/openssl-ruby-tests/patches/patch-test_openssl_test_asn1_rb

I should make a pull request to openssl-ruby to skip these tests for libressl 3.6 and later. It is somewhere low on my to do list.

**Comment by botovq** [comment]
I reported this upstream and consider this matter settled as far as we are concerned: https://github.com/ruby/openssl/issues/561
